### PR TITLE
add an argument `ifMiddleData` to produce middle data in an array

### PR DESCRIPTION
**Pull request by zry656565**
At most time, we do not need to show the result of edge detection, and the middle data is easier to be used.

### CODE REVIEW

**Comment by miguelmota** [comment]
went with different approach. Let me know if this doesn't work out for you.

``` javascript
  // Sobel constructor returns an Uint8ClampedArray with sobel data
  var sobelData = Sobel(imageData);

  // toImageData() return a new ImageData object
  var sobelImageData = sobelData.toImageData();
  context.putImageData(sobelImageData, 0, 0);
```

**Comment by zry656565** [comment]
Sorry for the delayed response. I had made some mistakes in my pull request, and your solution was suitable for me. Thanks :)

**Comment by zry656565** [comment]
Use this lib in https://github.com/zry656565/Polymation
Example: http://zry656565.github.io/Polymation/examples/

**Comment by miguelmota** [comment]
@zry656565 sweet :)

**Pull request closed without merging**
